hipestory/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('accounts/', include('users.urls', namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('feed-stories/', views.feed_stories, name='feed_stories'),
    path('feed-stories/<int:year>/<int:month>/<int:day>/<slug:slug>/', views.feed_story, name='feed_story'),
    path('tasks/', views.tasks, name='tasks'),
    path('tasks/<int:id>/', views.task, name='task'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('profile/change-avatar', views.change_avatar, name='change_avatar'),
    # path('profile/crop-avatar', views.crop_avatar, name='crop_avatar'),
    path('profile/add-avatar', views.add_avatar, name='add_avatar'),
    path('profile/delete-avatar', views.delete_avatar, name='delete_avatar'),
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('profile/new-story/', views.new_story, name='new_story'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    class Gender(models.TextChoices):
        MALE = 'Мужской', 'Мужской'
        FEMALE = 'Женский', 'Женский'

    last_name = models.CharField(verbose_name='Фамилия', max_length=150)
    first_name = models.CharField(verbose_name='Имя', max_length=150)
    surname = models.CharField(verbose_name='Отчество', max_length=150, blank=True)
    email = models.EmailField(verbose_name='Адрес электронной почты')
    avatar = models.ImageField(verbose_name='Аватарка', upload_to='images/users/', blank=True, null=True)
    age = models.IntegerField(verbose_name='Возраст', default=7)
    gender = models.CharField(verbose_name='Пол', max_length=7, choices=Gender.choices, default=Gender.MALE)

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username

    def get_full_name(self):
        full_name = f'{self.last_name} {self.first_name}'
        if self.surname:
            full_name = f'{full_name} {self.surname}'
        return full_name

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from users.models import User
from main.models import Story


class AddAvatarForm(forms.Form):
    avatar = forms.FileField(label='Добавить файл', widget=forms.FileInput(attrs={
        'class': 'content__input-file',
    }))


class CropAvatarForm(forms.Form):
    hidden = forms.CharField(required=False, widget=forms.HiddenInput(attrs={
        # 'style': 'opacity: 0;position: absolute;z-index: -1;'
    }))


class UserRegisterForm(UserCreationForm):
    last_name = forms.CharField(label='Фамилия', widget=forms.TextInput(attrs={
        'class': 'form__input'
    }))
    first_name = forms.CharField(label='Имя', widget=forms.TextInput(attrs={
        'class': 'form__input'
    }))
    surname = forms.CharField(max_length=255, required=False, label='Отчество(если есть)', widget=forms.TextInput(attrs={
        'class': 'form__input'
    }))
    username = forms.CharField(label='Имя пользователя', widget=forms.TextInput(attrs={
        'class': 'form__input'
    }))
    email = forms.EmailField(label='Адрес электронной почты', widget=forms.EmailInput(attrs={
        'class': 'form__input'
    }))
    age = forms.IntegerField(label='Возраст', widget=forms.NumberInput(attrs={
        'class': 'form__input'
    }))
    gender = forms.ChoiceField(label='Пол', choices=User.Gender.choices, widget=forms.Select(attrs={
        'class': 'form__input'
    }))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={
        'class': 'form__input'
    }))
    password2 = forms.CharField(label='Подтверждение пароля', widget=forms.PasswordInput(attrs={
        'class': 'form__input'
    }))

    class Meta:
        model = User
        fields = ('last_name', 'first_name', 'surname', 'username', 'email', 'age', 'gender', 'password1', 'password2')


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Имя пользователя', widget=forms.TextInput(attrs={
        'class': 'form__input'
    }))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={
        'class': 'form__input'
    }))


class NewStoryForm(forms.Form):
    title = forms.CharField(label='Заголовок', max_length=255, widget=forms.TextInput(attrs={
        'class': 'form__input'
    }))
    body = forms.CharField(label='Содержание', max_length=3000, widget=forms.Textarea(attrs={
        'class': 'form__input',
        'rows': 10,
        'cols': 0
    }))

users/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib import messages
from django.core.mail import send_mail

from hipestory import settings

from users.forms import AddAvatarForm, CropAvatarForm, UserRegisterForm, UserLoginForm, NewStoryForm


@login_required
def profile(request):
    return render(request, 'users/profile.html')


@login_required
def change_avatar(request):
    context = {'form': AddAvatarForm()}
    return render(request, 'users/change_avatar.html', context)


@login_required
def crop_avatar(request):
    if request.method == 'POST':
        form = CropAvatarForm(request.POST)
        print(request.POST, request.FILES)
        # user = request.user
        # user.avatar = form.cleaned_data.get('hidden')
        # user.save()
        # return redirect('users:profile')
    else:
        form = CropAvatarForm()
    context = {
        'form': form,
    }
    return render(request, 'users/crop_avatar.html', context)


@login_required
def add_avatar(request):
    form = AddAvatarForm(request.POST, files=request.FILES)
    if form.is_valid():
        avatar = form.files.get('avatar', '')
        if avatar:
            ext = avatar.name.split('.')[1].lower()
            if ext not in ['jpg', 'jpeg', 'png']:
                messages.error(request, 'Ошибка, неверный формат файла! (допустимые форматы файлов: PNG, JPEG, JPG)')
                return redirect('users:change_avatar')
            user = request.user
            avatar.name = f'{user.username}.png'
            user.avatar = avatar
            user.save()
            messages.success(request, 'Аватарка успешно изменена!')
            return redirect('users:profile')
        return redirect('users:change_avatar')
    messages.error(request, 'Вы не выбрали ни одного файла!')
    return redirect('users:change_avatar')


@login_required
def delete_avatar(request):
    user = request.user
    user.avatar = ''
    user.save()
    messages.success(request, 'Аватарка успешно удалена!')
    return redirect('users:profile')


class UserLoginView(SuccessMessageMixin, LoginView):
    form_class = UserLoginForm
    template_name = 'users/login.html'
    next_page = reverse_lazy('users:profile')
    success_message = 'Вы успешно вошли!'


class UserRegisterView(SuccessMessageMixin, CreateView):
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/register.html'
    success_message = 'Вы успешно зарегистрировались!'


class UserLogoutView(LogoutView):
    # next_page = reverse_lazy('users:logout')
    template_name = 'users/logout.html'


@login_required
def logout_user(request):
    logout(request.user)
    return render(request, 'users/logout.html')


@login_required
def new_story(request):
    if request.method == 'POST':
        form = NewStoryForm(request.POST)
        if form.is_valid():
            user = request.user
            send_mail('Предложение истории | Администрация HipeStory',
                      f'Пользователь с ником {user.username} пердлагает следующую историю:\n\n'
                      f'Заголовок: {form.cleaned_data.get("title")}\n\n'
                      f'Содержимое: {form.cleaned_data.get("body")}',
                      settings.DEFAULT_EMAIL_NAME, settings.ADMINISTRATION_EMAILS)
            messages.success(request,
                             'История успешно отправлена, '
                             'вскоре вы получите ответ на почту, '
                             'которую указали при регистрации.')
            return redirect('main:index')
    else:
        form = NewStoryForm()
    context = {
        'form': form
    }
    return render(request, 'users/new_story.html', context)

users/templates/users/change_avatar.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Изменение аватарки{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/change-avatar.style.css' %}">{% endblock %}

{% block content %}
    <nav class="navigation">
        <ul class="navigation__list">
            <li><a href="{% url 'main:index' %}" class="navigation__link">Главная</a></li>
            <li><a href="{% url 'users:profile' %}" class="navigation__link">Профиль</a></li>
            <li>Изменение аватарки</li>
        </ul>
    </nav>
    {% if messages %}
        {% for m in messages %}
            <div class="alert alert-{{ m.tags }}">{{ m }}</div>
        {% endfor %}
    {% endif %}
    <h1 class="content__title">Изменение аватарки</h1>
    <hr>
    <form action="{% url 'users:add_avatar' %}" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {% for f in form %}
            {{ f }}
            <label for="{{ f.id_for_label }}" id="inputFileLabel"
                   class="content__input-file-label"><span>{{ f.label }}</span></label>
        {% endfor %}
        <div class="content__buttons">
            <button type="submit" class="content__next">Далее</button>
            <a href="{% url 'users:profile' %}" class="content__back">Назад</a>
        </div>
    </form>
{% endblock %}

users/templates/users/crop_avatar.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Изменение аватарки{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/cropper.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/crop-avatar.style.css' %}">{% endblock %}

{% block content %}
    <nav class="navigation">
        <ul class="navigation__list">
            <li><a href="{% url 'main:index' %}" class="navigation__link">Главная</a></li>
            <li><a href="{% url 'users:profile' %}" class="navigation__link">Профиль</a></li>
            <li>Изменение аватарки</li>
        </ul>
    </nav>
    <h1 class="content__title">Изменение аватарки</h1>
    <hr>
    {% if user.avatar %}
        <div class="content__column">
            <div class="content__crop-image">
                <img src="{{ user.avatar.url }}" alt="Фото не выбрано" id="cutImage">
            </div>
            <form method="post" id="form" action="{% url 'users:crop_avatar' %}" enctype="multipart/form-data" class="content__buttons">
                {% csrf_token %}
                {{ form.hidden }}
                <button type="button" id="cropButton" class="content__crop">Обрезать</button>
                <a href="{% url 'users:profile' %}" class="content__cancel">Отмена</a>
            </form>
        </div>
    {% else %}
        <p style="margin: 20px 0 0 0;">Для того чтобы обрезать аватарку, нужно добавить ее</p>
    {% endif %}
{% endblock %}

{% block js %}
    <script src="{% static 'js/cropper.min.js' %}"></script>{% endblock %}

users/templates/users/login.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Вход{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/login.style.css' %}">{% endblock %}

{% block content %}
    <nav class="navigation">
        <ul class="navigation__list">
            <li><a href="{% url 'main:index' %}" class="navigation__link">Главная</a></li>
            <li>Вход</li>
        </ul>
    </nav>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}"
                 role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    {% if form.errors %}
        <div class="alert alert-error">Неверный логин или пароль, попробуйте еще раз.</div>
    {% endif %}
    <h1 class="content__title">Вход</h1>
    <hr>
    <form method="post" class="content__form form" novalidate>
        {% csrf_token %}
        {% for f in form %}
            <label class="form__label"><span>{{ f.label }}</span>{{ f }}</label>
        {% endfor %}
        <input type="submit" class="form__button" value="Войти">
    </form>
{% endblock %}

users/templates/users/logout.html
{% extends 'base.html' %}

{% block title %}Выход{% endblock %}

{% block content %}
    <nav class="navigation">
        <ul class="navigation__list">
            <li><a href="{% url 'main:index' %}" class="navigation__link">Главная</a></li>
            <li>Выход</li>
        </ul>
    </nav>
    <h1 class="content__title">Выход</h1>
    <hr>
    <p class="content__text" style="margin: 20px 0 0 0;">Выход успешно выполнен.</p>
{% endblock %}

users/templates/users/new_story.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Новая история | Профиль{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/new-story.style.css' %}">
{% endblock %}

{% block content %}
<nav class="navigation">
	<ul class="navigation__list">
		<li><a href="{% url 'main:index' %}" class="navigation__link">Главная</a></li>
		<li><a href="{% url 'users:profile' %}" class="navigation__link">Профиль</a></li>
		<li>Новая история</li>
	</ul>
</nav>
<h1 class="content__title">Новая история</h1>
<hr>
<form method="post" class="content__form form">
	{% for f in form %}
	<label class="form__label">
		{% csrf_token %}
		<span>{{ f.label }}</span>
		{{ f }}
	</label>
	{% endfor %}
	<input type="submit" class="form__button" value="Отправить">
</form>
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Профиль{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/profile.style.css' %}">{% endblock %}

{% block content %}
    <nav class="navigation">
        <ul class="navigation__list">
            <li><a href="{% url 'main:index' %}" class="navigation__link">Главная</a></li>
            <li>Профиль</li>
        </ul>
    </nav>
    {% if messages %}
        {% for m in messages %}
            <div class="alert alert-{{ m.tags }}">{{ m }}</div>
        {% endfor %}
    {% endif %}
    <h1 class="content__title">Профиль</h1>
    <hr>
    <div class="content__info info">
        <div class="info__row">
            <div id="profileImage" class="info__image">
                <img src="

                        {% if user.avatar %}{{ user.avatar.url }}{% else %}{% static 'img/profile/default-avatar.png' %}{% endif %}"
                     alt="фото профиля">
                <div id="profileImageMenu" class="info__image-function">
                    <a href="{% url 'users:change_avatar' %}" id="imageChangeButton"
                       class="info__image-change">Изменить</a>
                    <a href="{% url 'users:delete_avatar' %}" id="imageDeleteButton"
                       class="info__image-delete">Удалить</a>
                </div>
            </div>
            <div class="info__body">
                <h2 class="info__full-name">{{ user.get_full_name }}</h2>
                <p class="info__age">Возраст: <span>{{ user.age }}</span></p>
                <p class="info__gender">Пол: <span>{{ user.gender }}</span></p>
                <p class="info__mail">Почта: <span>{{ user.email }}</span></p>
            </div>
        </div>
    </div>
    <div class="content__buttons">
        {# <a href="" class="content__button-change-password">Сменить пароль</a>#}
        {# <a href="" class="content__button-change-data">Изменить данные</a>#}
        <a href="{% url 'users:new_story' %}" class="content__button">Предложить историю</a>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Регистрация{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/register.style.css' %}">{% endblock %}

{% block content %}
    <nav class="navigation">
        <ul class="navigation__list">
            <li><a href="{% url 'main:index' %}" class="navigation__link">Главная</a></li>
            <li>Регистрация</li>
        </ul>
    </nav>
    <h1 class="content__title">Регистрация</h1>
    <hr>
    <form method="post" novalidate class="content__form form">
        {% csrf_token %}
        {% for f in form %}
            <label class="form__label">
                <span>{{ f.label }}</span>
                {{ f }}
                {% if f.errors %}
                    {% for e in f.errors %}
                        <p class="form__error">{{ e }}</p>
                    {% endfor %}
                {% endif %}
            </label>
        {% endfor %}
        <input type="submit" class="form__button" value="Зарегистрироваться">
    </form>
{% endblock %}