hipestory/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('accounts/', include('users.urls', namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('feed-stories/', views.feed_stories, name='feed_stories'),
    path('feed-stories/<int:year>/<int:month>/<int:day>/<slug:slug>/', views.feed_story, name='feed_story'),
    path('tasks/', views.tasks, name='tasks'),
    path('tasks/<int:id>/', views.task, name='task'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('profile/change-avatar', views.change_avatar, name='change_avatar'),
    # path('profile/crop-avatar', views.crop_avatar, name='crop_avatar'),
    path('profile/add-avatar', views.add_avatar, name='add_avatar'),
    path('profile/delete-avatar', views.delete_avatar, name='delete_avatar'),
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('profile/new-story/', views.new_story, name='new_story'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Главная{% endblock %} | HipeStory</title>
    <link rel="stylesheet" href="{% static 'css/main.style.css' %}">
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/index.style.css' %}">{% endblock %}
    <link rel="icon" href="{% static 'img/icons/favicon.ico' %}">
</head>

<body>
<div class="wrapper">
    <header class="header">
        <div class="container">
            <div class="header__row">
                <div class="header__logo"><a href="{% url 'main:index' %}">HipeStory</a></div>
                <div class="header__menu menu">
                    <div id="menuIcon" class="menu__icon">
                        <span></span>
                    </div>
                    <nav id="menuBody" class="menu__body">
                        <ul class="menu__list">
                            <li><a href="{% url 'main:feed_stories' %}" class="menu__link">Лента</a></li>
                            {% if user.is_staff %}
                                <li><a href="{% url 'admin:index' %}" class="menu__link">Админ-панель</a></li>
                            {% endif %}
                            {% if user.is_authenticated %}
                                <li><a href="{% url 'users:profile' %}" class="menu__link">Профиль</a></li>
                                <li><a href="{% url 'users:logout' %}" class="menu__link">Выход</a></li>
                            {% else %}
                                <li><a href="{% url 'users:register' %}" class="menu__link">Регистрация</a></li>
                                <li><a href="{% url 'users:login' %}" class="menu__link">Вход</a></li>
                            {% endif %}
                            <li><a href="{% url 'main:tasks' %}" class="menu__link">Задания</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <main class="content">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </main>
    <footer class="footer">
        <div class="container">
            <div class="footer__row">
                <div class="footer__text">
                    © HipeStory
                </div>
            </div>
        </div>
    </footer>
</div>
{% block js %}{% endblock %}
<script src="{% static 'js/main.script.js' %}"></script>
</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <nav class="navigation">
        <ul class="navigation__list">
            <li>Главная</li>
        </ul>
    </nav>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}"
                 role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <h1 class="content__title">Главная</h1>
    <hr>
    <div class="block-1">
        <div class="block-1__row">
            <div class="block-1__body">
                <p>Lorem Ipsum - это текст-"рыба", часто используемый в печати и вэб-дизайне. Lorem Ipsum
                    является стандартной "рыбой" для текстов на латинице с начала XVI века.</p>
                <p>Lorem Ipsum - это текст-"рыба", часто используемый в печати и вэб-дизайне. Lorem Ipsum
                    является стандартной "рыбой" для текстов на латинице с начала XVI века. В то время некий
                    безымянный печатник создал большую коллекцию размеров и форм шрифтов, используя Lorem
                    Ipsum для распечатки образцов. Lorem Ipsum не только успешно пережил без заметных
                    изменений пять веков, но и перешагнул в электронный дизайн.</p>
            </div>
            <div class="block-1__image"><img src="{% static 'img/index/content_image.png' %}" alt=""></div>
        </div>
    </div>
    <div class="block-2">
        <p>Lorem Ipsum - это текст-"рыба", часто используемый в печати и вэб-дизайне. Lorem Ipsum является
            стандартной "рыбой" для текстов на латинице с начала XVI века. В то время некий безымянный
            печатник создал большую коллекцию размеров и форм шрифтов, используя Lorem Ipsum для распечатки
            образцов. Lorem Ipsum не только успешно пережил без заметных изменений пять веков, но и
            перешагнул в электронный дизайн. Его популяризации в новое время послужили публикация листов
            Letraset с образцами Lorem Ipsum в 60-х годах и, в более недавнее время, программы электронной
            вёрстки типа Aldus PageMaker, в шаблонах которых используется Lorem Ipsum. Lorem Ipsum - это
            текст-"рыба", часто используемый в печати и вэб-дизайне. Lorem Ipsum является стандартной
            "рыбой" для текстов на латинице с начала XVI века.</p>
    </div>
{% endblock %}